opening_hours:
  monday: "8:00 AM - 10:00 PM"
  tuesday: "8:00 AM - 10:00 PM"
  wednesday: "8:00 AM - 10:00 PM"
  thursday: "8:00 AM - 10:00 PM"
  friday: "8:00 AM - 11:00 PM"
  saturday: "9:00 AM - 11:00 PM"
  sunday: "9:00 AM - 9:00 PM"

menu:
  pizza:
    price: 24.99
    description: "Margherita, Pepperoni, Hawaiian"
  burger:
    price: 18.99
    description: "Cheeseburger, Veggie, Double Meat"
  salad:
    price: 12.99
    description: "Caesar, Greek, Garden"